import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="manifest"
          href={`${
            process.env.NODE_ENV == "production" ? "/hk-bus" : ""
          }/manifest.json`}
        />
      </Head>
      <body className={`${inter.className} w-screen h-screen bg-gray-800`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
